# Generated by Django 5.2.9 on 2025-12-29 14:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Tenant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-safe identifier", max_length=100, unique=True
                    ),
                ),
                (
                    "subdomain",
                    models.CharField(blank=True, max_length=100, unique=True),
                ),
                (
                    "custom_domain",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                (
                    "plan",
                    models.CharField(
                        choices=[
                            ("free", "Free"),
                            ("starter", "Starter"),
                            ("professional", "Professional"),
                            ("enterprise", "Enterprise"),
                        ],
                        default="free",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("suspended", "Suspended"),
                            ("trial", "Trial"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("trial_ends_at", models.DateTimeField(blank=True, null=True)),
                ("subscription_ends_at", models.DateTimeField(blank=True, null=True)),
                ("max_users", models.PositiveIntegerField(default=5)),
                ("max_projects", models.PositiveIntegerField(default=10)),
                ("max_storage_gb", models.PositiveIntegerField(default=5)),
                ("current_users", models.PositiveIntegerField(default=0)),
                ("current_projects", models.PositiveIntegerField(default=0)),
                ("storage_used_bytes", models.BigIntegerField(default=0)),
                (
                    "features",
                    models.JSONField(
                        default=dict, help_text="Feature flags for this tenant"
                    ),
                ),
                (
                    "branding",
                    models.JSONField(
                        default=dict, help_text="Custom branding configuration"
                    ),
                ),
                (
                    "database_name",
                    models.CharField(
                        blank=True,
                        help_text="Separate database for enterprise tenants",
                        max_length=100,
                    ),
                ),
                (
                    "schema_name",
                    models.CharField(
                        blank=True,
                        help_text="Database schema for isolation",
                        max_length=100,
                    ),
                ),
                ("settings", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tenant",
                        to="users.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tenant",
                "verbose_name_plural": "Tenants",
                "ordering": ["company__name"],
            },
        ),
        migrations.CreateModel(
            name="TenantAuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("action", models.CharField(max_length=50)),
                ("resource_type", models.CharField(max_length=50)),
                ("resource_id", models.CharField(blank=True, max_length=255)),
                ("details", models.JSONField(default=dict)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admin_audit_logs",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TenantBranding",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "logo_light",
                    models.URLField(blank=True, help_text="Logo for light backgrounds"),
                ),
                (
                    "logo_dark",
                    models.URLField(blank=True, help_text="Logo for dark backgrounds"),
                ),
                ("favicon", models.URLField(blank=True)),
                ("primary_color", models.CharField(default="#3B82F6", max_length=7)),
                ("secondary_color", models.CharField(default="#6366F1", max_length=7)),
                ("accent_color", models.CharField(default="#10B981", max_length=7)),
                ("font_family", models.CharField(default="Inter", max_length=100)),
                ("heading_font", models.CharField(blank=True, max_length=100)),
                ("email_header_image", models.URLField(blank=True)),
                ("email_footer_text", models.TextField(blank=True)),
                ("custom_css", models.TextField(blank=True)),
                ("terms_url", models.URLField(blank=True)),
                ("privacy_url", models.URLField(blank=True)),
                ("support_email", models.EmailField(blank=True, max_length=254)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="branding_config",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tenant Branding",
                "verbose_name_plural": "Tenant Brandings",
            },
        ),
        migrations.CreateModel(
            name="TenantInvitation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "Admin"),
                            ("manager", "Manager"),
                            ("employee", "Employee"),
                        ],
                        default="employee",
                        max_length=20,
                    ),
                ),
                ("token", models.CharField(max_length=100, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("expired", "Expired"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("expires_at", models.DateTimeField()),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "accepted_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="accepted_invitations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "invited_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_invitations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invitations",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TenantUsageStats",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField()),
                ("active_users", models.PositiveIntegerField(default=0)),
                ("tasks_created", models.PositiveIntegerField(default=0)),
                ("tasks_completed", models.PositiveIntegerField(default=0)),
                ("projects_active", models.PositiveIntegerField(default=0)),
                ("progress_updates", models.PositiveIntegerField(default=0)),
                ("api_requests", models.PositiveIntegerField(default=0)),
                ("files_uploaded", models.PositiveIntegerField(default=0)),
                ("storage_added_bytes", models.BigIntegerField(default=0)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_stats",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "unique_together": {("tenant", "date")},
            },
        ),
    ]
