# Generated by Django 5.2.9 on 2025-12-29 14:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0002_initial"),
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationDigest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("hourly", "Hourly"),
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                        ],
                        max_length=20,
                    ),
                ),
                ("notifications", models.JSONField(default=list)),
                ("notification_count", models.PositiveIntegerField(default=0)),
                ("period_start", models.DateTimeField()),
                ("period_end", models.DateTimeField()),
                ("is_sent", models.BooleanField(default=False)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_digests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-period_end"],
            },
        ),
        migrations.CreateModel(
            name="NotificationRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "trigger_type",
                    models.CharField(
                        choices=[
                            ("task_overdue", "Task Becomes Overdue"),
                            ("task_overdue_days", "Task Overdue by X Days"),
                            ("task_deadline_approaching", "Task Deadline Approaching"),
                            ("task_status_change", "Task Status Changed"),
                            ("task_assigned", "Task Assigned"),
                            ("task_blocked", "Task Blocked"),
                            ("task_completed", "Task Completed"),
                            ("progress_submitted", "Progress Update Submitted"),
                            ("progress_below_threshold", "Progress Below Threshold"),
                            ("no_progress_days", "No Progress for X Days"),
                            (
                                "project_deadline_approaching",
                                "Project Deadline Approaching",
                            ),
                            ("project_status_change", "Project Status Changed"),
                            ("project_health_critical", "Project Health Critical"),
                            ("budget_threshold", "Budget Threshold Reached"),
                            ("expense_submitted", "Expense Submitted"),
                            ("over_allocation", "Resource Over-Allocated"),
                            ("capacity_warning", "Capacity Warning"),
                            ("schedule", "Scheduled Time"),
                            ("custom", "Custom Condition"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "conditions",
                    models.JSONField(
                        default=dict,
                        help_text="Condition parameters (e.g., {'days_overdue': 2})",
                    ),
                ),
                (
                    "apply_to_assigned_only",
                    models.BooleanField(
                        default=True,
                        help_text="Only trigger for tasks assigned to the user",
                    ),
                ),
                (
                    "channels",
                    models.JSONField(
                        default=list, help_text="List of channels to notify through"
                    ),
                ),
                ("notify_self", models.BooleanField(default=True)),
                ("notify_assignee", models.BooleanField(default=False)),
                ("notify_manager", models.BooleanField(default=False)),
                ("notify_team", models.BooleanField(default=False)),
                (
                    "additional_recipients",
                    models.JSONField(
                        default=list,
                        help_text="Additional user IDs or emails to notify",
                    ),
                ),
                (
                    "message_template",
                    models.TextField(
                        blank=True,
                        help_text="Custom message template with placeholders like {{task.title}}",
                    ),
                ),
                (
                    "cooldown_minutes",
                    models.PositiveIntegerField(
                        default=60,
                        help_text="Minimum minutes between notifications for same trigger",
                    ),
                ),
                (
                    "max_notifications_per_day",
                    models.PositiveIntegerField(
                        default=10,
                        help_text="Maximum notifications per day for this rule",
                    ),
                ),
                (
                    "schedule_cron",
                    models.CharField(
                        blank=True,
                        help_text="Cron expression for scheduled triggers",
                        max_length=100,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("last_triggered", models.DateTimeField(blank=True, null=True)),
                ("trigger_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_rules",
                        to="users.company",
                    ),
                ),
                (
                    "projects",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Apply only to these projects (empty = all)",
                        related_name="notification_rules",
                        to="projects.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_rules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-is_active", "name"],
            },
        ),
        migrations.CreateModel(
            name="NotificationDelivery",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("channel", models.CharField(max_length=20)),
                ("title", models.CharField(max_length=255)),
                ("message", models.TextField()),
                ("related_object_type", models.CharField(blank=True, max_length=50)),
                ("related_object_id", models.CharField(blank=True, max_length=255)),
                ("action_url", models.URLField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("delivered", "Delivered"),
                            ("failed", "Failed"),
                            ("read", "Read"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_deliveries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliveries",
                        to="notifications.notificationrule",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification Delivery",
                "verbose_name_plural": "Notification Deliveries",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SMSConfiguration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("twilio", "Twilio"),
                            ("nexmo", "Nexmo/Vonage"),
                            ("aws_sns", "AWS SNS"),
                            ("messagebird", "MessageBird"),
                        ],
                        max_length=20,
                    ),
                ),
                ("account_sid", models.CharField(max_length=255)),
                ("auth_token", models.CharField(max_length=255)),
                ("from_number", models.CharField(max_length=20)),
                ("monthly_limit", models.PositiveIntegerField(default=1000)),
                ("messages_sent_this_month", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sms_config",
                        to="users.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "SMS Configuration",
                "verbose_name_plural": "SMS Configurations",
            },
        ),
        migrations.CreateModel(
            name="PushSubscription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("endpoint", models.URLField(max_length=500)),
                ("p256dh_key", models.CharField(max_length=255)),
                ("auth_key", models.CharField(max_length=255)),
                ("user_agent", models.CharField(blank=True, max_length=500)),
                ("device_name", models.CharField(blank=True, max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                ("last_used", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="push_subscriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "endpoint")},
            },
        ),
    ]
