# Generated by Django 5.2.9 on 2025-12-29 14:14

import django.db.models.deletion
import integrations.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("progress", "0002_initial"),
        ("projects", "0002_initial"),
        ("tasks", "0002_initial"),
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="APIKey",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("key", models.CharField(db_index=True, max_length=64, unique=True)),
                (
                    "key_prefix",
                    models.CharField(
                        help_text="First 8 chars for identification", max_length=8
                    ),
                ),
                (
                    "permissions",
                    models.JSONField(
                        default=dict,
                        help_text="API permissions: {'read': [...], 'write': [...]}",
                    ),
                ),
                (
                    "rate_limit",
                    models.PositiveIntegerField(
                        default=1000, help_text="Requests per hour"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("last_used", models.DateTimeField(blank=True, null=True)),
                ("request_count", models.PositiveIntegerField(default=0)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_keys",
                        to="users.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_api_keys",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "API Key",
                "verbose_name_plural": "API Keys",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CalendarConnection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("google", "Google Calendar"),
                            ("outlook", "Microsoft Outlook"),
                            ("apple", "Apple Calendar"),
                        ],
                        max_length=20,
                    ),
                ),
                ("access_token", models.TextField()),
                ("refresh_token", models.TextField(blank=True)),
                ("token_expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "calendar_id",
                    models.CharField(
                        blank=True, help_text="External calendar ID", max_length=255
                    ),
                ),
                ("calendar_name", models.CharField(blank=True, max_length=255)),
                ("sync_tasks", models.BooleanField(default=True)),
                ("sync_deadlines", models.BooleanField(default=True)),
                ("sync_milestones", models.BooleanField(default=True)),
                ("import_events_as_tasks", models.BooleanField(default=False)),
                ("two_way_sync", models.BooleanField(default=False)),
                (
                    "sync_status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("error", "Error"),
                            ("disconnected", "Disconnected"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("last_sync", models.DateTimeField(blank=True, null=True)),
                ("last_sync_error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calendar_connections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("user", "provider")},
            },
        ),
        migrations.CreateModel(
            name="FileAttachment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("task", "Task"),
                            ("project", "Project"),
                            ("progress_update", "Progress Update"),
                            ("comment", "Comment"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "file",
                    models.FileField(upload_to=integrations.models.upload_to_path),
                ),
                ("original_filename", models.CharField(max_length=255)),
                ("file_size", models.BigIntegerField(default=0)),
                ("mime_type", models.CharField(blank=True, max_length=100)),
                (
                    "storage_provider",
                    models.CharField(
                        choices=[
                            ("local", "Local Storage"),
                            ("s3", "Amazon S3"),
                            ("gcs", "Google Cloud Storage"),
                            ("azure", "Azure Blob Storage"),
                            ("gdrive", "Google Drive"),
                        ],
                        default="local",
                        max_length=20,
                    ),
                ),
                (
                    "external_url",
                    models.URLField(blank=True, help_text="URL for cloud-stored files"),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                ("is_latest", models.BooleanField(default=True)),
                ("description", models.TextField(blank=True)),
                ("tags", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="users.company",
                    ),
                ),
                (
                    "parent_version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="child_versions",
                        to="integrations.fileattachment",
                    ),
                ),
                (
                    "progress_update",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="file_attachments",
                        to="progress.progressupdate",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="file_attachments",
                        to="projects.project",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="file_attachments",
                        to="tasks.task",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uploaded_files",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FileVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("version_number", models.PositiveIntegerField()),
                ("file", models.FileField(upload_to="attachments/versions/")),
                ("file_size", models.BigIntegerField(default=0)),
                ("change_summary", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "attachment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="integrations.fileattachment",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-version_number"],
            },
        ),
        migrations.CreateModel(
            name="WebhookEndpoint",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("url", models.URLField()),
                (
                    "secret",
                    models.CharField(
                        blank=True, help_text="Webhook signing secret", max_length=64
                    ),
                ),
                (
                    "events",
                    models.JSONField(
                        default=list, help_text="List of event types to send"
                    ),
                ),
                ("custom_headers", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("last_triggered", models.DateTimeField(blank=True, null=True)),
                ("failure_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="webhook_endpoints",
                        to="users.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WebhookDelivery",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("event_type", models.CharField(max_length=50)),
                ("payload", models.JSONField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("retrying", "Retrying"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("response_status", models.PositiveIntegerField(blank=True, null=True)),
                ("response_body", models.TextField(blank=True)),
                ("error_message", models.TextField(blank=True)),
                ("attempt_count", models.PositiveIntegerField(default=0)),
                ("next_retry", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                (
                    "webhook",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliveries",
                        to="integrations.webhookendpoint",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="APIRequestLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("method", models.CharField(max_length=10)),
                ("endpoint", models.CharField(max_length=500)),
                ("request_body", models.JSONField(blank=True, null=True)),
                ("response_status", models.PositiveIntegerField()),
                ("response_time_ms", models.PositiveIntegerField()),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "api_key",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="request_logs",
                        to="integrations.apikey",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["api_key", "created_at"],
                        name="integration_api_key_c89132_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="CalendarEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("external_event_id", models.CharField(max_length=255)),
                ("external_calendar_id", models.CharField(blank=True, max_length=255)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                ("all_day", models.BooleanField(default=False)),
                ("location", models.CharField(blank=True, max_length=500)),
                (
                    "sync_direction",
                    models.CharField(
                        choices=[
                            ("imported", "Imported"),
                            ("exported", "Exported"),
                            ("bidirectional", "Bidirectional"),
                        ],
                        default="exported",
                        max_length=20,
                    ),
                ),
                ("last_synced", models.DateTimeField(auto_now=True)),
                ("external_updated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="integrations.calendarconnection",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="synced_calendar_events",
                        to="projects.project",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="synced_calendar_events",
                        to="tasks.task",
                    ),
                ),
            ],
            options={
                "ordering": ["start_time"],
                "unique_together": {("connection", "external_event_id")},
            },
        ),
        migrations.AddIndex(
            model_name="fileattachment",
            index=models.Index(
                fields=["content_type", "task"], name="integration_content_1a5955_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fileattachment",
            index=models.Index(
                fields=["content_type", "project"],
                name="integration_content_fc3663_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="fileattachment",
            index=models.Index(
                fields=["company", "content_type"],
                name="integration_company_a748f6_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="fileversion",
            unique_together={("attachment", "version_number")},
        ),
    ]
