# Generated by Django 5.2.9 on 2025-12-26 16:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("analytics", "__first__"),
        ("projects", "0002_initial"),
        ("tasks", "0002_initial"),
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BurnoutIndicator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("moderate", "Moderate"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        max_length=20,
                    ),
                ),
                ("risk_score", models.FloatField(help_text="Risk score 0-100")),
                (
                    "factors",
                    models.JSONField(
                        default=dict, help_text="Breakdown of contributing factors"
                    ),
                ),
                ("avg_hours_per_week", models.FloatField(default=0)),
                ("consecutive_overtime_weeks", models.IntegerField(default=0)),
                ("tasks_overdue", models.IntegerField(default=0)),
                ("no_break_days", models.IntegerField(default=0)),
                ("meeting_hours", models.FloatField(default=0)),
                ("progress_update_sentiment", models.FloatField(default=0)),
                (
                    "recommendations",
                    models.JSONField(
                        default=list, help_text="AI-generated recommendations"
                    ),
                ),
                ("manager_notified", models.BooleanField(default=False)),
                ("manager_notified_at", models.DateTimeField(blank=True, null=True)),
                ("is_addressed", models.BooleanField(default=False)),
                ("addressed_at", models.DateTimeField(blank=True, null=True)),
                ("addressed_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="burnout_indicators",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CalendarEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("task_deadline", "Task Deadline"),
                            ("meeting", "Meeting"),
                            ("milestone", "Milestone"),
                            ("reminder", "Reminder"),
                            ("external", "External Event"),
                        ],
                        max_length=20,
                    ),
                ),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                ("all_day", models.BooleanField(default=False)),
                ("is_recurring", models.BooleanField(default=False)),
                (
                    "recurrence_rule",
                    models.CharField(
                        blank=True, help_text="iCal RRULE format", max_length=255
                    ),
                ),
                ("external_id", models.CharField(blank=True, max_length=255)),
                ("external_source", models.CharField(blank=True, max_length=50)),
                ("external_link", models.URLField(blank=True)),
                ("is_synced", models.BooleanField(default=False)),
                ("last_synced", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calendar_events",
                        to="projects.project",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calendar_events",
                        to="tasks.task",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calendar_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["start_time"],
            },
        ),
        migrations.CreateModel(
            name="ChatIntegration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("slack", "Slack"),
                            ("teams", "Microsoft Teams"),
                            ("discord", "Discord"),
                        ],
                        max_length=20,
                    ),
                ),
                ("access_token", models.TextField()),
                ("refresh_token", models.TextField(blank=True)),
                ("token_expires_at", models.DateTimeField(blank=True, null=True)),
                ("workspace_id", models.CharField(max_length=255)),
                ("workspace_name", models.CharField(max_length=255)),
                ("bot_user_id", models.CharField(blank=True, max_length=255)),
                ("default_channel_id", models.CharField(blank=True, max_length=255)),
                ("notify_task_assigned", models.BooleanField(default=True)),
                ("notify_task_completed", models.BooleanField(default=True)),
                ("notify_daily_standup", models.BooleanField(default=True)),
                ("standup_time", models.TimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_integrations",
                        to="users.company",
                    ),
                ),
            ],
            options={
                "unique_together": {("company", "platform")},
            },
        ),
        migrations.CreateModel(
            name="ChatCommand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "command_type",
                    models.CharField(
                        choices=[
                            ("create_task", "Create Task"),
                            ("update_task", "Update Task"),
                            ("log_time", "Log Time"),
                            ("get_status", "Get Status"),
                            ("list_tasks", "List Tasks"),
                            ("standup", "Daily Standup"),
                        ],
                        max_length=50,
                    ),
                ),
                ("raw_text", models.TextField()),
                ("parsed_data", models.JSONField(default=dict)),
                ("chat_user_id", models.CharField(max_length=255)),
                ("response_text", models.TextField(blank=True)),
                ("is_processed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "linked_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "integration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commands",
                        to="automation.chatintegration",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DependencyBottleneck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "blocking_count",
                    models.IntegerField(
                        default=0, help_text="Number of tasks blocked by this task"
                    ),
                ),
                (
                    "cascade_delay_days",
                    models.FloatField(
                        default=0,
                        help_text="Estimated cascade delay in days if this task is late",
                    ),
                ),
                (
                    "affected_deadline",
                    models.DateTimeField(
                        blank=True,
                        help_text="The final deadline that would be affected",
                        null=True,
                    ),
                ),
                (
                    "delay_probability",
                    models.FloatField(
                        default=0,
                        help_text="Probability this task will cause delays (0-1)",
                    ),
                ),
                (
                    "suggested_actions",
                    models.JSONField(
                        default=list,
                        help_text="AI-suggested actions to prevent bottleneck",
                    ),
                ),
                ("is_resolved", models.BooleanField(default=False)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bottlenecks",
                        to="tasks.task",
                    ),
                ),
            ],
            options={
                "ordering": ["-severity", "-cascade_delay_days"],
            },
        ),
        migrations.CreateModel(
            name="EscalationRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "trigger_type",
                    models.CharField(
                        choices=[
                            ("overdue", "Task Overdue"),
                            ("blocked", "Task Blocked"),
                            ("no_progress", "No Progress Updates"),
                            ("approaching_deadline", "Approaching Deadline"),
                            ("high_priority_blocked", "High Priority Blocked"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "trigger_after_hours",
                    models.IntegerField(
                        default=24,
                        help_text="Hours after condition is met before escalation triggers",
                    ),
                ),
                (
                    "priority_filter",
                    models.CharField(
                        blank=True,
                        help_text="Only escalate tasks with this priority (leave blank for all)",
                        max_length=20,
                    ),
                ),
                ("escalate_to_manager", models.BooleanField(default=True)),
                ("send_email", models.BooleanField(default=True)),
                ("send_notification", models.BooleanField(default=True)),
                ("send_slack", models.BooleanField(default=False)),
                ("auto_reassign", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="escalation_rules",
                        to="users.company",
                    ),
                ),
                (
                    "escalate_to_users",
                    models.ManyToManyField(
                        blank=True,
                        related_name="escalation_rules_recipient",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project_filter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Escalation Rule",
                "verbose_name_plural": "Escalation Rules",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Escalation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("acknowledged", "Acknowledged"),
                            ("in_progress", "In Progress"),
                            ("resolved", "Resolved"),
                            ("dismissed", "Dismissed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("reason", models.TextField()),
                (
                    "suggested_actions",
                    models.JSONField(
                        default=list, help_text="AI-suggested actions to resolve"
                    ),
                ),
                ("resolution_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "escalated_to",
                    models.ManyToManyField(
                        related_name="received_escalations", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_escalations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="escalations",
                        to="tasks.task",
                    ),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="escalations",
                        to="automation.escalationrule",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GitIntegration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("github", "GitHub"),
                            ("gitlab", "GitLab"),
                            ("bitbucket", "Bitbucket"),
                        ],
                        max_length=20,
                    ),
                ),
                ("access_token", models.TextField()),
                ("refresh_token", models.TextField(blank=True)),
                ("token_expires_at", models.DateTimeField(blank=True, null=True)),
                ("organization", models.CharField(blank=True, max_length=255)),
                ("sync_issues", models.BooleanField(default=True)),
                ("sync_pull_requests", models.BooleanField(default=True)),
                ("auto_create_tasks", models.BooleanField(default=False)),
                ("auto_update_progress", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="git_integrations",
                        to="users.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("company", "platform")},
            },
        ),
        migrations.CreateModel(
            name="GitRepository",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("repo_id", models.CharField(max_length=255)),
                ("repo_name", models.CharField(max_length=255)),
                ("repo_full_name", models.CharField(max_length=500)),
                ("repo_url", models.URLField()),
                ("webhook_id", models.CharField(blank=True, max_length=255)),
                ("webhook_secret", models.CharField(blank=True, max_length=255)),
                ("sync_enabled", models.BooleanField(default=True)),
                ("last_synced", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "integration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="repositories",
                        to="automation.gitintegration",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="git_repositories",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "unique_together": {("integration", "repo_id")},
            },
        ),
        migrations.CreateModel(
            name="LocationBasedTracking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("radius_meters", models.IntegerField(default=100)),
                ("auto_start", models.BooleanField(default=True)),
                ("auto_stop", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "default_task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="tasks.task",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="location_tracking_configs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Location Tracking Config",
                "verbose_name_plural": "Location Tracking Configs",
            },
        ),
        migrations.CreateModel(
            name="LocationCheckIn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("check_in_time", models.DateTimeField()),
                ("check_out_time", models.DateTimeField(blank=True, null=True)),
                ("check_in_lat", models.FloatField()),
                ("check_in_lon", models.FloatField()),
                ("check_out_lat", models.FloatField(blank=True, null=True)),
                ("check_out_lon", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "location_config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checkins",
                        to="automation.locationbasedtracking",
                    ),
                ),
                (
                    "time_entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="analytics.timeentry",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="location_checkins",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-check_in_time"],
            },
        ),
        migrations.CreateModel(
            name="PersonalizedDashboard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("is_default", models.BooleanField(default=False)),
                (
                    "layout",
                    models.JSONField(
                        default=list, help_text="Dashboard widget layout configuration"
                    ),
                ),
                ("auto_refresh", models.BooleanField(default=True)),
                ("refresh_interval_seconds", models.IntegerField(default=300)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dashboards",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-is_default", "name"],
            },
        ),
        migrations.CreateModel(
            name="DashboardWidget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "widget_type",
                    models.CharField(
                        choices=[
                            ("task_summary", "Task Summary"),
                            ("progress_chart", "Progress Chart"),
                            ("time_tracking", "Time Tracking"),
                            ("upcoming_deadlines", "Upcoming Deadlines"),
                            ("team_activity", "Team Activity"),
                            ("project_health", "Project Health"),
                            ("productivity_metrics", "Productivity Metrics"),
                            ("burnout_indicator", "Burnout Indicator"),
                            ("ai_insights", "AI Insights"),
                            ("calendar", "Calendar"),
                            ("notifications", "Recent Notifications"),
                            ("quick_actions", "Quick Actions"),
                            ("custom_chart", "Custom Chart"),
                        ],
                        max_length=50,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255)),
                ("position_x", models.IntegerField(default=0)),
                ("position_y", models.IntegerField(default=0)),
                ("width", models.IntegerField(default=4)),
                ("height", models.IntegerField(default=2)),
                ("config", models.JSONField(default=dict)),
                ("is_visible", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "dashboard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="widgets",
                        to="automation.personalizeddashboard",
                    ),
                ),
            ],
            options={
                "ordering": ["position_y", "position_x"],
            },
        ),
        migrations.CreateModel(
            name="ResourceAllocationSuggestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "suggestion_type",
                    models.CharField(
                        choices=[
                            ("reassign", "Reassign Task"),
                            ("redistribute", "Redistribute Workload"),
                            ("hire", "Suggest Hiring"),
                            ("skill_gap", "Skill Gap Detected"),
                            ("overload", "Overload Warning"),
                        ],
                        max_length=50,
                    ),
                ),
                ("reason", models.TextField()),
                (
                    "impact_score",
                    models.FloatField(help_text="Expected positive impact (0-100)"),
                ),
                (
                    "confidence_score",
                    models.FloatField(help_text="AI confidence in suggestion (0-1)"),
                ),
                ("supporting_data", models.JSONField(default=dict)),
                ("is_applied", models.BooleanField(default=False)),
                ("is_dismissed", models.BooleanField(default=False)),
                ("applied_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "applied_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="applied_suggestions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resource_suggestions",
                        to="users.company",
                    ),
                ),
                (
                    "from_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resource_from_suggestions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tasks.task",
                    ),
                ),
                (
                    "to_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resource_to_suggestions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-impact_score", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ScheduleSuggestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("suggested_start", models.DateTimeField()),
                ("suggested_end", models.DateTimeField()),
                ("reason", models.TextField()),
                ("confidence_score", models.FloatField(default=0.5)),
                (
                    "conflicts_avoided",
                    models.JSONField(
                        default=list, help_text="List of events that would conflict"
                    ),
                ),
                ("is_accepted", models.BooleanField(default=False)),
                ("is_dismissed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule_suggestions",
                        to="tasks.task",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule_suggestions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-confidence_score", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VoiceCommand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "command_type",
                    models.CharField(
                        choices=[
                            ("create_task", "Create Task"),
                            ("update_progress", "Update Progress"),
                            ("log_time", "Log Time"),
                            ("get_summary", "Get Summary"),
                            ("list_tasks", "List Tasks"),
                            ("add_note", "Add Note"),
                        ],
                        max_length=50,
                    ),
                ),
                ("raw_transcript", models.TextField()),
                ("parsed_intent", models.JSONField(default=dict)),
                ("is_successful", models.BooleanField(default=False)),
                ("result_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "linked_task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="tasks.task",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="voice_commands",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Workflow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "trigger_type",
                    models.CharField(
                        choices=[
                            ("task_status_change", "Task Status Changed"),
                            ("task_created", "Task Created"),
                            ("task_assigned", "Task Assigned"),
                            ("task_overdue", "Task Becomes Overdue"),
                            ("task_blocked", "Task Blocked"),
                            ("progress_update", "Progress Update Submitted"),
                            ("deadline_approaching", "Deadline Approaching"),
                            ("project_status_change", "Project Status Changed"),
                            ("schedule", "Scheduled Time"),
                            ("webhook", "Webhook Received"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "trigger_config",
                    models.JSONField(
                        default=dict,
                        help_text="Configuration for the trigger (e.g., specific status values)",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("execution_count", models.IntegerField(default=0)),
                ("last_executed", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workflows",
                        to="users.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_workflows",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project_filter",
                    models.ForeignKey(
                        blank=True,
                        help_text="Only trigger for tasks in this project (optional)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Workflow",
                "verbose_name_plural": "Workflows",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WorkflowAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("send_notification", "Send In-App Notification"),
                            ("send_email", "Send Email"),
                            ("send_slack", "Send Slack Message"),
                            ("send_teams", "Send Teams Message"),
                            ("send_webhook", "Send Webhook"),
                            ("update_task_status", "Update Task Status"),
                            ("update_task_priority", "Update Task Priority"),
                            ("assign_task", "Assign Task"),
                            ("create_subtask", "Create Subtask"),
                            ("add_comment", "Add Comment"),
                            ("update_dependent_tasks", "Update Dependent Tasks"),
                            ("recalculate_timeline", "Recalculate Timeline"),
                            ("update_project_status", "Update Project Status"),
                            ("escalate_to_manager", "Escalate to Manager"),
                            ("create_escalation", "Create Escalation Ticket"),
                            ("sync_calendar", "Sync to Calendar"),
                            ("update_github_issue", "Update GitHub Issue"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "config",
                    models.JSONField(default=dict, help_text="Action configuration"),
                ),
                ("order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actions",
                        to="automation.workflow",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="WorkflowCondition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "condition_type",
                    models.CharField(
                        choices=[
                            ("field_equals", "Field Equals Value"),
                            ("field_contains", "Field Contains Value"),
                            ("field_in_list", "Field In List"),
                            ("user_role", "User Has Role"),
                            ("time_range", "Within Time Range"),
                            ("custom", "Custom Expression"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "config",
                    models.JSONField(default=dict, help_text="Condition configuration"),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conditions",
                        to="automation.workflow",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="WorkflowExecution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("trigger_data", models.JSONField(default=dict)),
                ("result_data", models.JSONField(default=dict)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="executions",
                        to="automation.workflow",
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="GitEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("push", "Push"),
                            ("pull_request", "Pull Request"),
                            ("issue", "Issue"),
                            ("commit", "Commit"),
                            ("branch", "Branch"),
                            ("release", "Release"),
                        ],
                        max_length=50,
                    ),
                ),
                ("event_id", models.CharField(max_length=255)),
                ("event_data", models.JSONField(default=dict)),
                ("is_processed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "linked_task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="git_events",
                        to="tasks.task",
                    ),
                ),
                (
                    "repository",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="automation.gitrepository",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("repository", "event_id")},
            },
        ),
        migrations.CreateModel(
            name="TaskDependency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dependency_type",
                    models.CharField(
                        choices=[
                            ("finish_to_start", "Finish to Start"),
                            ("start_to_start", "Start to Start"),
                            ("finish_to_finish", "Finish to Finish"),
                            ("start_to_finish", "Start to Finish"),
                        ],
                        default="finish_to_start",
                        max_length=20,
                    ),
                ),
                (
                    "lag_days",
                    models.IntegerField(
                        default=0,
                        help_text="Days of lag (positive) or lead (negative) time",
                    ),
                ),
                (
                    "auto_adjust_dates",
                    models.BooleanField(
                        default=True,
                        help_text="Automatically adjust successor dates when predecessor changes",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "predecessor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="successor_dependencies",
                        to="tasks.task",
                    ),
                ),
                (
                    "successor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="predecessor_dependencies",
                        to="tasks.task",
                    ),
                ),
            ],
            options={
                "verbose_name": "Task Dependency",
                "verbose_name_plural": "Task Dependencies",
                "unique_together": {("predecessor", "successor")},
            },
        ),
        migrations.CreateModel(
            name="WorkloadSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("active_tasks", models.IntegerField(default=0)),
                ("completed_tasks", models.IntegerField(default=0)),
                ("overdue_tasks", models.IntegerField(default=0)),
                ("blocked_tasks", models.IntegerField(default=0)),
                ("hours_worked", models.FloatField(default=0)),
                ("meeting_hours", models.FloatField(default=0)),
                ("overtime_hours", models.FloatField(default=0)),
                ("tasks_started", models.IntegerField(default=0)),
                ("tasks_completed_on_time", models.IntegerField(default=0)),
                ("progress_updates", models.IntegerField(default=0)),
                ("avg_sentiment_score", models.FloatField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workload_snapshots",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "unique_together": {("user", "date")},
            },
        ),
    ]
