# Generated by Django 5.2.7 on 2025-11-30 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProgressAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="progress_attachments/")),
                ("filename", models.CharField(max_length=255)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="ProgressComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProgressUpdate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "progress_percentage",
                    models.IntegerField(
                        default=0, help_text="Current completion percentage (0-100)"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("on_track", "On Track"),
                            ("at_risk", "At Risk"),
                            ("blocked", "Blocked"),
                            ("waiting", "Waiting"),
                            ("completed", "Completed"),
                        ],
                        default="on_track",
                        max_length=20,
                    ),
                ),
                (
                    "work_done",
                    models.TextField(help_text="Description of work completed"),
                ),
                (
                    "next_steps",
                    models.TextField(blank=True, help_text="Planned next steps"),
                ),
                (
                    "blockers",
                    models.TextField(blank=True, help_text="Any blockers or issues"),
                ),
                (
                    "hours_worked",
                    models.FloatField(
                        default=0, help_text="Hours worked since last update"
                    ),
                ),
                (
                    "links",
                    models.TextField(
                        blank=True, help_text="Links to PRs, docs, etc. (one per line)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Progress Update",
                "verbose_name_plural": "Progress Updates",
                "ordering": ["-created_at"],
            },
        ),
    ]
