# Generated by Django 5.2.9 on 2025-12-29 14:14

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("integrations", "0001_initial"),
        ("projects", "0002_initial"),
        ("tasks", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("description", models.CharField(max_length=500)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("labor", "Labor"),
                            ("software", "Software/Licenses"),
                            ("hardware", "Hardware"),
                            ("travel", "Travel"),
                            ("consulting", "Consulting"),
                            ("marketing", "Marketing"),
                            ("infrastructure", "Infrastructure"),
                            ("misc", "Miscellaneous"),
                        ],
                        max_length=30,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("expense_date", models.DateField()),
                ("vendor", models.CharField(blank=True, max_length=255)),
                ("invoice_number", models.CharField(blank=True, max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Approval"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("paid", "Paid"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True)),
                ("is_billable", models.BooleanField(default=False)),
                ("billed_to_client", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_expenses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expenses",
                        to="projects.project",
                    ),
                ),
                (
                    "receipt",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="expense_receipts",
                        to="integrations.fileattachment",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submitted_expenses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="expenses",
                        to="tasks.task",
                    ),
                ),
            ],
            options={
                "ordering": ["-expense_date"],
            },
        ),
        migrations.CreateModel(
            name="ProjectBudget",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "budget_type",
                    models.CharField(
                        choices=[
                            ("fixed", "Fixed Budget"),
                            ("time_and_materials", "Time & Materials"),
                            ("retainer", "Retainer"),
                        ],
                        default="fixed",
                        max_length=30,
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("USD", "US Dollar"),
                            ("EUR", "Euro"),
                            ("GBP", "British Pound"),
                            ("INR", "Indian Rupee"),
                            ("JPY", "Japanese Yen"),
                            ("CAD", "Canadian Dollar"),
                            ("AUD", "Australian Dollar"),
                        ],
                        default="USD",
                        max_length=3,
                    ),
                ),
                (
                    "total_budget",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                (
                    "labor_budget",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                (
                    "expense_budget",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                (
                    "contingency_budget",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Reserve for unexpected costs",
                        max_digits=15,
                    ),
                ),
                (
                    "spent_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                (
                    "committed_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Approved but not yet spent",
                        max_digits=15,
                    ),
                ),
                (
                    "warning_threshold_percentage",
                    models.PositiveIntegerField(
                        default=80,
                        help_text="Alert when budget reaches this percentage",
                    ),
                ),
                (
                    "critical_threshold_percentage",
                    models.PositiveIntegerField(
                        default=95, help_text="Critical alert threshold"
                    ),
                ),
                (
                    "is_locked",
                    models.BooleanField(
                        default=False, help_text="Prevent further changes"
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="budget",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Project Budget",
                "verbose_name_plural": "Project Budgets",
            },
        ),
        migrations.CreateModel(
            name="BudgetVarianceReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("report_date", models.DateField()),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                ("planned_spend", models.DecimalField(decimal_places=2, max_digits=15)),
                ("actual_spend", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "variance_amount",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                (
                    "variance_percentage",
                    models.DecimalField(decimal_places=2, max_digits=6),
                ),
                ("category_breakdown", models.JSONField(default=dict)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "generated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "budget",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variance_reports",
                        to="resources.projectbudget",
                    ),
                ),
            ],
            options={
                "ordering": ["-report_date"],
            },
        ),
        migrations.CreateModel(
            name="BudgetAlert",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("warning", "Warning Threshold"),
                            ("critical", "Critical Threshold"),
                            ("over_budget", "Over Budget"),
                            ("forecast", "Forecast Alert"),
                        ],
                        max_length=20,
                    ),
                ),
                ("message", models.TextField()),
                ("threshold_percentage", models.PositiveIntegerField()),
                (
                    "actual_percentage",
                    models.DecimalField(decimal_places=2, max_digits=6),
                ),
                ("is_acknowledged", models.BooleanField(default=False)),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "acknowledged_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "budget",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="resources.projectbudget",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ResourceAllocation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "allocation_type",
                    models.CharField(
                        choices=[
                            ("project", "Project Allocation"),
                            ("task", "Task Allocation"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "allocated_hours_per_week",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=5
                    ),
                ),
                (
                    "percentage_allocation",
                    models.PositiveIntegerField(
                        default=100, help_text="Percentage of time allocated (0-100)"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        blank=True,
                        help_text="Role in this project/task",
                        max_length=100,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_allocations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resource_allocations",
                        to="projects.project",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resource_allocations",
                        to="tasks.task",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allocations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="CapacityWarning",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "warning_type",
                    models.CharField(
                        choices=[
                            ("over_allocation", "Over Allocation"),
                            ("near_capacity", "Near Capacity"),
                            ("skill_mismatch", "Skill Mismatch"),
                            ("timeline_conflict", "Timeline Conflict"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "Info"),
                            ("warning", "Warning"),
                            ("critical", "Critical"),
                        ],
                        max_length=20,
                    ),
                ),
                ("message", models.TextField()),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                (
                    "allocated_hours",
                    models.DecimalField(decimal_places=2, max_digits=6),
                ),
                ("capacity_hours", models.DecimalField(decimal_places=2, max_digits=6)),
                ("over_allocation_percentage", models.PositiveIntegerField(default=0)),
                ("is_acknowledged", models.BooleanField(default=False)),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "acknowledged_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="acknowledged_warnings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="capacity_warnings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "allocation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="resources.resourceallocation",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserCapacity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "hours_per_week",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("40.00"), max_digits=5
                    ),
                ),
                (
                    "hourly_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Internal hourly rate for cost calculations",
                        max_digits=10,
                    ),
                ),
                (
                    "billable_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="External billable hourly rate",
                        max_digits=10,
                    ),
                ),
                ("skills", models.JSONField(default=list, help_text="List of skills")),
                (
                    "time_off_days",
                    models.JSONField(
                        default=list, help_text="List of dates when user is unavailable"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="capacity",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Capacity",
                "verbose_name_plural": "User Capacities",
            },
        ),
        migrations.AddIndex(
            model_name="resourceallocation",
            index=models.Index(
                fields=["user", "start_date", "end_date"],
                name="resources_r_user_id_d393c6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="resourceallocation",
            index=models.Index(
                fields=["project", "is_active"], name="resources_r_project_7a5a87_idx"
            ),
        ),
    ]
