# Generated by Django 5.2.9 on 2025-12-29 14:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DashboardTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "target_role",
                    models.CharField(
                        choices=[
                            ("admin", "Admin"),
                            ("manager", "Manager"),
                            ("employee", "Employee"),
                            ("all", "All Roles"),
                        ],
                        default="all",
                        max_length=20,
                    ),
                ),
                ("layout", models.JSONField(default=dict)),
                (
                    "widgets",
                    models.JSONField(
                        default=list, help_text="List of widget configurations"
                    ),
                ),
                ("thumbnail", models.URLField(blank=True)),
                ("is_featured", models.BooleanField(default=False)),
                ("is_premium", models.BooleanField(default=False)),
                ("usage_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-is_featured", "name"],
            },
        ),
        migrations.CreateModel(
            name="WidgetTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("widget_type", models.CharField(max_length=50)),
                ("default_config", models.JSONField(default=dict)),
                ("default_filters", models.JSONField(default=dict)),
                ("default_size", models.CharField(default="medium", max_length=20)),
                ("category", models.CharField(blank=True, max_length=50)),
                ("icon", models.CharField(blank=True, max_length=50)),
                ("is_premium", models.BooleanField(default=False)),
                ("usage_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["category", "name"],
            },
        ),
        migrations.CreateModel(
            name="Dashboard",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "layout",
                    models.JSONField(
                        default=dict, help_text="Grid layout configuration for widgets"
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False, help_text="Default dashboard for user"
                    ),
                ),
                ("is_shared", models.BooleanField(default=False)),
                ("shared_with_team", models.BooleanField(default=False)),
                ("theme", models.CharField(default="default", max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_dashboards",
                        to="users.company",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_dashboards",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-is_default", "name"],
                "unique_together": {("user", "name")},
            },
        ),
        migrations.CreateModel(
            name="DashboardWidget",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "widget_type",
                    models.CharField(
                        choices=[
                            ("task_completion_rate", "Task Completion Rate"),
                            ("task_status_chart", "Task Status Chart"),
                            ("tasks_by_priority", "Tasks by Priority"),
                            ("overdue_tasks", "Overdue Tasks"),
                            ("my_tasks", "My Tasks"),
                            ("team_tasks", "Team Tasks"),
                            ("time_spent_vs_estimated", "Time Spent vs Estimated"),
                            ("time_tracking_summary", "Time Tracking Summary"),
                            ("weekly_hours", "Weekly Hours Chart"),
                            ("billable_hours", "Billable Hours"),
                            ("project_health", "Project Health Score"),
                            ("project_progress", "Project Progress"),
                            ("project_timeline", "Project Timeline (Gantt)"),
                            ("project_milestones", "Project Milestones"),
                            ("team_performance", "Team Performance"),
                            ("team_workload", "Team Workload"),
                            ("resource_allocation", "Resource Allocation"),
                            ("budget_overview", "Budget Overview"),
                            ("expense_breakdown", "Expense Breakdown"),
                            ("budget_variance", "Budget Variance"),
                            ("recent_activity", "Recent Activity"),
                            ("recent_updates", "Recent Progress Updates"),
                            ("notifications", "Notifications"),
                            ("burndown_chart", "Burndown Chart"),
                            ("velocity_chart", "Velocity Chart"),
                            ("trend_chart", "Custom Trend Chart"),
                            ("calendar", "Calendar View"),
                            ("quick_actions", "Quick Actions"),
                            ("custom_metric", "Custom Metric"),
                            ("text_note", "Text/Note Widget"),
                            ("iframe", "Embedded Content"),
                        ],
                        max_length=50,
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("subtitle", models.CharField(blank=True, max_length=200)),
                ("position_x", models.PositiveIntegerField(default=0)),
                ("position_y", models.PositiveIntegerField(default=0)),
                ("width", models.PositiveIntegerField(default=1)),
                ("height", models.PositiveIntegerField(default=1)),
                (
                    "size",
                    models.CharField(
                        choices=[
                            ("small", "Small (1x1)"),
                            ("medium", "Medium (2x1)"),
                            ("large", "Large (2x2)"),
                            ("wide", "Wide (3x1)"),
                            ("tall", "Tall (1x2)"),
                            ("full", "Full Width (4x1)"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                (
                    "config",
                    models.JSONField(
                        default=dict, help_text="Widget-specific configuration options"
                    ),
                ),
                (
                    "filters",
                    models.JSONField(
                        default=dict,
                        help_text="Data filters (project, date range, team members, etc.)",
                    ),
                ),
                ("auto_refresh", models.BooleanField(default=True)),
                ("refresh_interval_seconds", models.PositiveIntegerField(default=300)),
                ("is_visible", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "dashboard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="widgets",
                        to="dashboards.dashboard",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "position_y", "position_x"],
            },
        ),
        migrations.CreateModel(
            name="WidgetData",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("data", models.JSONField(default=dict)),
                ("last_calculated", models.DateTimeField(auto_now=True)),
                ("expires_at", models.DateTimeField()),
                (
                    "widget",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cached_data",
                        to="dashboards.dashboardwidget",
                    ),
                ),
            ],
            options={
                "verbose_name": "Widget Data Cache",
                "verbose_name_plural": "Widget Data Caches",
            },
        ),
    ]
