# Generated by Django 5.2.9 on 2025-12-29 14:14

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "user_email",
                    models.EmailField(
                        help_text="Preserved for history if user is deleted",
                        max_length=254,
                    ),
                ),
                ("user_name", models.CharField(max_length=255)),
                ("object_id", models.CharField(max_length=255)),
                (
                    "object_repr",
                    models.CharField(
                        help_text="String representation of object", max_length=500
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Created"),
                            ("update", "Updated"),
                            ("delete", "Deleted"),
                            ("view", "Viewed"),
                            ("login", "Login"),
                            ("logout", "Logout"),
                            ("export", "Exported"),
                            ("import", "Imported"),
                            ("assign", "Assigned"),
                            ("unassign", "Unassigned"),
                            ("approve", "Approved"),
                            ("reject", "Rejected"),
                            ("submit", "Submitted"),
                            ("comment", "Commented"),
                            ("attach", "Attached File"),
                            ("status_change", "Status Changed"),
                            ("permission_change", "Permission Changed"),
                            ("bulk_update", "Bulk Updated"),
                            ("revert", "Reverted"),
                        ],
                        max_length=30,
                    ),
                ),
                ("action_category", models.CharField(blank=True, max_length=50)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "Info"),
                            ("warning", "Warning"),
                            ("critical", "Critical"),
                        ],
                        default="info",
                        max_length=20,
                    ),
                ),
                (
                    "changes",
                    models.JSONField(
                        default=dict,
                        help_text="Dict of {field: {'old': value, 'new': value}}",
                    ),
                ),
                (
                    "old_values",
                    models.JSONField(default=dict, help_text="Complete old state"),
                ),
                (
                    "new_values",
                    models.JSONField(default=dict, help_text="Complete new state"),
                ),
                (
                    "message",
                    models.TextField(
                        blank=True, help_text="Human-readable description"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(default=dict, help_text="Additional context data"),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=500)),
                ("request_id", models.CharField(blank=True, max_length=100)),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_logs",
                        to="users.company",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit Log",
                "verbose_name_plural": "Audit Logs",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="AuditLogSearch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "filters",
                    models.JSONField(default=dict, help_text="Saved filter criteria"),
                ),
                ("is_subscribed", models.BooleanField(default=False)),
                ("notify_on_match", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.company"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_audit_searches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ChangeSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("snapshot_data", models.JSONField()),
                (
                    "snapshot_type",
                    models.CharField(
                        choices=[("before", "Before"), ("after", "After")],
                        default="after",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "audit_log",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshots",
                        to="audit.auditlog",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["company", "timestamp"], name="audit_audit_company_80eef3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["user", "timestamp"], name="audit_audit_user_id_e8be02_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["content_type", "object_id"],
                name="audit_audit_content_4c2ead_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["action", "timestamp"], name="audit_audit_action_2a1328_idx"
            ),
        ),
    ]
